<?php

use Illuminate\Database\Seeder;

class ContactsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        \DB::table('contacts')->insert(array (
            0 =>
            array (
                'id' => 1,
                'name' => 'Robert S. McCroy',
                'email' => 'robertsmccroy@dayrep.com ',
                'primary_number' => '703-517-9656',
                'secondary_number' => '',
                'address' => '4244 Gregory Lane',
                'zipcode' => '22102',
                'city' => 'McLean',
                'state' => 'VA',
                'company_name' => 'Merrill Lynch',
                'is_guest' => 0,
                'group_id' => 1,
                'user_id' => 1,
                'industry_id' => 1,
                'created_at' => '2017-11-26 13:51:10',
                'updated_at' => '2017-11-26 13:51:10',
            ),
            1 =>
            array (
                'id' => 2,
                'name' => 'Charles J. Marquart',
                'email' => 'CharlesJMarquart@dayrep.com',
                'primary_number' => '703-767-8007',
                'secondary_number' => '',
                'address' => '3753 Tea Berry Lane',
                'zipcode' => '20148',
                'city' => 'Ashburn',
                'state' => 'VA',
                'company_name' => 'Rogersound Labs',
                'is_guest' => 0,
                'group_id' => 1,
                'user_id' => 1,
                'industry_id' => 2,
                'created_at' => '2017-11-26 13:51:10',
                'updated_at' => '2017-11-26 13:51:10',
            ),
            2 =>
            array (
                'id' => 3,
                'name' => 'Angela D. Smith',
                'email' => 'AngelaDSmith@dayrep.com',
                'primary_number' => '240-386-9508',
                'secondary_number' => '',
                'address' => '6608 Green Ash ct',
                'zipcode' => '22152',
                'city' => 'Falls Church',
                'state' => 'VA',
                'company_name' => 'Pomeroy\'s',
                'is_guest' => 0,
                'group_id' => 1,
                'user_id' => 1,
                'industry_id' => 3,
                'created_at' => '2017-11-26 13:51:10',
                'updated_at' => '2017-11-26 13:51:10',
            ),
            3 =>
            array (
                'id' => 4,
                'name' => 'Brandon B. Fox',
                'email' => 'BrandonBFox@teleworm.us',
                'primary_number' => '240-224-5125',
                'secondary_number' => '',
                'address' => '1521 Freshour Circle',
                'zipcode' => '22152',
                'city' => 'Centreville',
                'state' => 'VA',
                'company_name' => 'White Coffee Pot',
                'is_guest' => 0,
                'group_id' => 1,
                'user_id' => 1,
                'industry_id' => 4,
                'created_at' => '2017-11-26 13:51:10',
                'updated_at' => '2017-11-26 13:51:10',
            ),
            4 =>
            array (
                'id' => 5,
                'name' => 'Timmy D. Owenby',
                'email' => 'TimmyDOwenby@jourrapide.com',
                'primary_number' => '703-616-3241',
                'secondary_number' => '',
                'address' => '3508 Parrill Court',
                'zipcode' => '22102',
                'city' => 'McLean',
                'state' => 'VA',
                'company_name' => 'Brendle\'s',
                'is_guest' => 0,
                'group_id' => 1,
                'user_id' => 1,
                'industry_id' => 5,
                'created_at' => '2017-11-26 13:51:10',
                'updated_at' => '2017-11-26 13:51:10',
            ),
            5 =>
            array (
                'id' => 6,
                'name' => 'Chelsie G. Barker',
                'email' => 'ChelsieGBarker@dayrep.com',
                'primary_number' => '703-955-6819',
                'secondary_number' => '',
                'address' => '3368 Quilly Lane',
                'zipcode' => '20148',
                'city' => 'Ashburn',
                'state' => 'VA',
                'company_name' => 'Action Auto',
                'is_guest' => 0,
                'group_id' => 1,
                'user_id' => 1,
                'industry_id' => 1,
                'created_at' => '2017-11-26 13:51:10',
                'updated_at' => '2017-11-26 13:51:10',
            ),
            6 =>
            array (
                'id' => 7,
                'name' => 'Martha J. Isaac',
                'email' => 'MarthaJIsaac@armyspy.com',
                'primary_number' => '240-294-1599',
                'secondary_number' => '',
                'address' => '2632 Red Dog Road',
                'zipcode' => '22152',
                'city' => 'Springfield',
                'state' => 'VA',
                'company_name' => 'L.L. Berger',
                'is_guest' => 0,
                'group_id' => 1,
                'user_id' => 1,
                'industry_id' => 1,
                'created_at' => '2017-11-26 13:51:10',
                'updated_at' => '2017-11-26 13:51:10',
            ),
            7 =>
            array (
                'id' => 8,
                'name' => 'Clinton B. Turner',
                'email' => 'ClintonBTurner@dayrep.com',
                'primary_number' => '240-258-2963',
                'secondary_number' => '',
                'address' => '1030 Cecil Street',
                'zipcode' => '22152',
                'city' => 'Springfield',
                'state' => 'VA',
                'company_name' => 'J. Riggings',
                'is_guest' => 0,
                'group_id' => 1,
                'user_id' => 1,
                'industry_id' => 1,
                'created_at' => '2017-11-26 13:51:10',
                'updated_at' => '2017-11-26 13:51:10',
            ),
            8 =>
            array (
                'id' => 9,
                'name' => 'Richard K. Ellison',
                'email' => 'RichardKEllison@teleworm.us',
                'primary_number' => '703-462-8233',
                'secondary_number' => '',
                'address' => '376 Melody Lane',
                'zipcode' => '22102',
                'city' => 'McLean',
                'state' => 'VA',
                'company_name' => 'Merrill Lynch',
                'is_guest' => 0,
                'group_id' => 1,
                'user_id' => 1,
                'industry_id' => 1,
                'created_at' => '2017-11-26 13:51:10',
                'updated_at' => '2017-11-26 13:51:10',
            ),
            9 =>
            array (
                'id' => 10,
                'name' => 'Nancy W. Kinnard',
                'email' => 'NancyWKinnard@jourrapide.com',
                'primary_number' => '703-249-6770',
                'secondary_number' => '',
                'address' => '547 Elk Rd Little',
                'zipcode' => '20148',
                'city' => 'Ashburn',
                'state' => 'VA',
                'company_name' => 'Purity Supreme',
                'is_guest' => 0,
                'group_id' => 1,
                'user_id' => 1,
                'industry_id' => 1,
                'created_at' => '2017-11-26 13:51:10',
                'updated_at' => '2017-11-26 13:51:10',
            ),
            10 =>
            array (
                'id' => 11,
                'name' => 'Nicole C. Manners',
                'email' => 'NicoleCManners@teleworm.us',
                'primary_number' => '240-678-4838',
                'secondary_number' => '',
                'address' => '3205 West Street',
                'zipcode' => '22152',
                'city' => 'Springfield',
                'state' => 'VA',
                'company_name' => 'DGS HomeSource',
                'is_guest' => 0,
                'group_id' => 1,
                'user_id' => 1,
                'industry_id' => 1,
                'created_at' => '2017-11-26 13:51:10',
                'updated_at' => '2017-11-26 13:51:10',
            ),
            11 =>
            array (
                'id' => 12,
                'name' => 'Erin S. Wright',
                'email' => 'ErinSWright@teleworm.us',
                'primary_number' => '240-264-1726',
                'secondary_number' => '',
                'address' => '4343 Oakridge Lane',
                'zipcode' => '22152',
                'city' => 'Springfield',
                'state' => 'VA',
                'company_name' => 'Grodins',
                'is_guest' => 0,
                'group_id' => 1,
                'user_id' => 1,
                'industry_id' => 1,
                'created_at' => '2017-11-26 13:51:10',
                'updated_at' => '2017-11-26 13:51:10',
            ),
            12 =>
            array (
                'id' => 13,
                'name' => 'Donald L. Moore',
                'email' => 'DonaldLMoore@jourrapide.com',
                'primary_number' => '703-864-4096',
                'secondary_number' => '',
                'address' => '1588 Poe Road',
                'zipcode' => '22102',
                'city' => 'McLean',
                'state' => 'VA',
                'company_name' => 'Action Auto',
                'is_guest' => 0,
                'group_id' => 1,
                'user_id' => 1,
                'industry_id' => 1,
                'created_at' => '2017-11-26 13:51:10',
                'updated_at' => '2017-11-26 13:51:10',
            ),
            13 =>
            array (
                'id' => 14,
                'name' => 'Dann S. King',
                'email' => 'DannSKing@armyspy.com',
                'primary_number' => '703-755-1488',
                'secondary_number' => '',
                'address' => '333 Perine Street',
                'zipcode' => '20148',
                'city' => 'Ashburn',
                'state' => 'VA',
                'company_name' => 'Miller & Rhoads',
                'is_guest' => 0,
                'group_id' => 1,
                'user_id' => 1,
                'industry_id' => 1,
                'created_at' => '2017-11-26 13:51:10',
                'updated_at' => '2017-11-26 13:51:10',
            ),
            14 =>
            array (
                'id' => 15,
                'name' => 'Debby R. Baldwin',
                'email' => 'DebbyRBaldwin@rhyta.com',
                'primary_number' => '240-665-9433',
                'secondary_number' => '',
                'address' => '4175 Drainer Avenue',
                'zipcode' => '22152',
                'city' => 'Springfield',
                'state' => 'VA',
                'company_name' => 'Playworld',
                'is_guest' => 0,
                'group_id' => 1,
                'user_id' => 1,
                'industry_id' => 1,
                'created_at' => '2017-11-26 13:51:10',
                'updated_at' => '2017-11-26 13:51:10',
            ),
            15 =>
            array (
                'id' => 16,
                'name' => 'Charles S. Muir',
                'email' => 'CharlesSMuir@jourrapide.com',
                'primary_number' => '240-471-8384',
                'secondary_number' => '',
                'address' => '72 Benson Park Drive',
                'zipcode' => '22152',
                'city' => 'Springfield',
                'state' => 'VA',
                'company_name' => 'Team Uno',
                'is_guest' => 0,
                'group_id' => 1,
                'user_id' => 1,
                'industry_id' => 1,
                'created_at' => '2017-11-26 13:51:10',
                'updated_at' => '2017-11-26 13:51:10',
            ),
            16 =>
            array (
                'id' => 17,
                'name' => 'Jeffrey K. Depriest',
                'email' => 'JeffreyKDepriest@dayrep.com',
                'primary_number' => '703-989-0383',
                'secondary_number' => '',
                'address' => '3788 Hummingbird Way',
                'zipcode' => '22102',
                'city' => 'McLean',
                'state' => 'VA',
                'company_name' => 'Planetbiz',
                'is_guest' => 0,
                'group_id' => 1,
                'user_id' => 1,
                'industry_id' => 1,
                'created_at' => '2017-11-26 13:51:10',
                'updated_at' => '2017-11-26 13:51:10',
            ),
            17 =>
            array (
                'id' => 18,
                'name' => 'Peter S. Whitmore',
                'email' => 'PeterSWhitmore@dayrep.com',
                'primary_number' => '703-315-0238',
                'secondary_number' => '',
                'address' => '3824 Ashmor Drive',
                'zipcode' => '20148',
                'city' => 'Ashburn',
                'state' => 'VA',
                'company_name' => 'Jacob Reed and Sons',
                'is_guest' => 0,
                'group_id' => 1,
                'user_id' => 1,
                'industry_id' => 1,
                'created_at' => '2017-11-26 13:51:10',
                'updated_at' => '2017-11-26 13:51:10',
            ),
            18 =>
            array (
                'id' => 19,
                'name' => 'Krystal G. Ugarte',
                'email' => 'KrystalGUgarte@armyspy.com',
                'primary_number' => '240-255-7228',
                'secondary_number' => '',
                'address' => '4273 Catherine Drive',
                'zipcode' => '22152',
                'city' => 'Springfield',
                'state' => 'VA',
                'company_name' => 'Payless Cashways',
                'is_guest' => 0,
                'group_id' => 1,
                'user_id' => 1,
                'industry_id' => 1,
                'created_at' => '2017-11-26 13:51:10',
                'updated_at' => '2017-11-26 13:51:10',
            ),
            19 =>
            array (
                'id' => 20,
                'name' => 'Daniel D. Phillips',
                'email' => 'DanielDPhillips@dayrep.com',
                'primary_number' => '240-925-8985',
                'secondary_number' => '',
                'address' => '1446 Hope Street',
                'zipcode' => '22152',
                'city' => 'Springfield',
                'state' => 'VA',
                'company_name' => 'A Plus Lawn Care',
                'is_guest' => 0,
                'group_id' => 1,
                'user_id' => 1,
                'industry_id' => 1,
                'created_at' => '2017-11-26 13:51:10',
                'updated_at' => '2017-11-26 13:51:10',
            ),
            20 =>
            array (
                'id' => 21,
                'name' => 'Michael Reyes',
                'email' => 'michael.p.reyes@ml.com ',
                'primary_number' => '703-663-2909',
                'secondary_number' => '',
                'address' => '8300 Greensboro Drive, 1st Floor',
                'zipcode' => '22102',
                'city' => 'McLean',
                'state' => 'VA',
                'company_name' => 'Merrill Lynch',
                'is_guest' => 0,
                'group_id' => 4,
                'user_id' => 1,
                'industry_id' => 1,
                'created_at' => '2017-11-26 13:51:10',
                'updated_at' => '2017-11-26 13:51:10',
            ),
            21 =>
            array (
                'id' => 22,
                'name' => 'Seong Bae',
                'email' => 'seong@lnidigital.com',
                'primary_number' => '703-955-6819',
                'secondary_number' => '',
                'address' => '42466 Legacy Park Drive',
                'zipcode' => '20148',
                'city' => 'Ashburn',
                'state' => 'VA',
                'company_name' => 'LNI Digital Marketing',
                'is_guest' => 0,
                'group_id' => 4,
                'user_id' => 1,
                'industry_id' => 1,
                'created_at' => '2017-11-26 13:51:10',
                'updated_at' => '2017-11-26 13:51:10',
            ),
            22 =>
            array (
                'id' => 23,
                'name' => 'Sunny Luk',
                'email' => 'Lukfinancialgroup@gmail.com',
                'primary_number' => '240-386-9508',
                'secondary_number' => '',
                'address' => '6608 Green Ash ct',
                'zipcode' => '22152',
                'city' => 'Springfield',
                'state' => 'VA',
                'company_name' => 'Luk Financial Group',
                'is_guest' => 0,
                'group_id' => 4,
                'user_id' => 1,
                'industry_id' => 1,
                'created_at' => '2017-11-26 13:51:10',
                'updated_at' => '2017-11-26 13:51:10',
            ),
            23 =>
            array (
                'id' => 24,
                'name' => 'Dave Estep',
                'email' => 'destep@olmstedfoundation.org',
                'primary_number' => '240-386-9508',
                'secondary_number' => '',
                'address' => '6608 Green Ash ct',
                'zipcode' => '22152',
                'city' => 'Springfield',
                'state' => 'VA',
                'company_name' => 'The Olmsted Foundation',
                'is_guest' => 1,
                'group_id' => 4,
                'user_id' => 1,
                'industry_id' => 1,
                'created_at' => '2017-11-26 13:51:10',
                'updated_at' => '2017-11-26 13:51:10',
            )
        ));
    }
}
