<?php

use Illuminate\Database\Seeder;

class ContactsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        \DB::table('contacts')->insert(array (
            0 =>
            array (
                'id' => 1,
                'name' => 'Robert S. McCroy',
                'email' => 'robertsmccroy@dayrep.com ',
                'primary_number' => '703-517-9656',
                'secondary_number' => '',
                'address' => '4244 Gregory Lane',
                'zipcode' => '22102',
                'city' => 'McLean',
                'state' => 'VA',
                'company_name' => 'Merrill Lynch',
                'status' => 1,
                'group_id' => 1,
                'user_id' => 1,
                'industry_id' => 1,
                'created_at' => '2017-11-26 13:51:10',
                'updated_at' => '2017-11-26 13:51:10',
            ),
            1 =>
            array (
                'id' => 2,
                'name' => 'Charles J. Marquart',
                'email' => 'CharlesJMarquart@dayrep.com',
                'primary_number' => '703-767-8007',
                'secondary_number' => '',
                'address' => '3753 Tea Berry Lane',
                'zipcode' => '20148',
                'city' => 'Ashburn',
                'state' => 'VA',
                'company_name' => 'Rogersound Labs',
                'status' => 1,
                'group_id' => 1,
                'user_id' => 1,
                'industry_id' => 2,
                'created_at' => '2017-11-26 13:51:10',
                'updated_at' => '2017-11-26 13:51:10',
            ),
            2 =>
            array (
                'id' => 3,
                'name' => 'Angela D. Smith',
                'email' => 'AngelaDSmith@dayrep.com',
                'primary_number' => '240-386-9508',
                'secondary_number' => '',
                'address' => '6608 Green Ash ct',
                'zipcode' => '22152',
                'city' => 'Falls Church',
                'state' => 'VA',
                'company_name' => 'Pomeroy\'s',
                'status' => 1,
                'group_id' => 1,
                'user_id' => 1,
                'industry_id' => 3,
                'created_at' => '2017-11-26 13:51:10',
                'updated_at' => '2017-11-26 13:51:10',
            ),
            3 =>
            array (
                'id' => 4,
                'name' => 'Brandon B. Fox',
                'email' => 'BrandonBFox@teleworm.us',
                'primary_number' => '240-224-5125',
                'secondary_number' => '',
                'address' => '1521 Freshour Circle',
                'zipcode' => '22152',
                'city' => 'Centreville',
                'state' => 'VA',
                'company_name' => 'White Coffee Pot',
                'status' => 1,
                'group_id' => 1,
                'user_id' => 1,
                'industry_id' => 4,
                'created_at' => '2017-11-26 13:51:10',
                'updated_at' => '2017-11-26 13:51:10',
            ),
            4 =>
            array (
                'id' => 5,
                'name' => 'Timmy D. Owenby',
                'email' => 'TimmyDOwenby@jourrapide.com',
                'primary_number' => '703-616-3241',
                'secondary_number' => '',
                'address' => '3508 Parrill Court',
                'zipcode' => '22102',
                'city' => 'McLean',
                'state' => 'VA',
                'company_name' => 'Brendle\'s',
                'status' => 1,
                'group_id' => 1,
                'user_id' => 1,
                'industry_id' => 5,
                'created_at' => '2017-11-26 13:51:10',
                'updated_at' => '2017-11-26 13:51:10',
            ),
            5 =>
            array (
                'id' => 6,
                'name' => 'Chelsie G. Barker',
                'email' => 'ChelsieGBarker@dayrep.com',
                'primary_number' => '703-955-6819',
                'secondary_number' => '',
                'address' => '3368 Quilly Lane',
                'zipcode' => '20148',
                'city' => 'Ashburn',
                'state' => 'VA',
                'company_name' => 'Action Auto',
                'status' => 1,
                'group_id' => 1,
                'user_id' => 1,
                'industry_id' => 1,
                'created_at' => '2017-11-26 13:51:10',
                'updated_at' => '2017-11-26 13:51:10',
            ),
            6 =>
            array (
                'id' => 7,
                'name' => 'Martha J. Isaac',
                'email' => 'MarthaJIsaac@armyspy.com',
                'primary_number' => '240-294-1599',
                'secondary_number' => '',
                'address' => '2632 Red Dog Road',
                'zipcode' => '22152',
                'city' => 'Springfield',
                'state' => 'VA',
                'company_name' => 'L.L. Berger',
                'status' => 1,
                'group_id' => 1,
                'user_id' => 1,
                'industry_id' => 1,
                'created_at' => '2017-11-26 13:51:10',
                'updated_at' => '2017-11-26 13:51:10',
            ),
            7 =>
            array (
                'id' => 8,
                'name' => 'Clinton B. Turner',
                'email' => 'ClintonBTurner@dayrep.com',
                'primary_number' => '240-258-2963',
                'secondary_number' => '',
                'address' => '1030 Cecil Street',
                'zipcode' => '22152',
                'city' => 'Springfield',
                'state' => 'VA',
                'company_name' => 'J. Riggings',
                'status' => 1,
                'group_id' => 1,
                'user_id' => 1,
                'industry_id' => 1,
                'created_at' => '2017-11-26 13:51:10',
                'updated_at' => '2017-11-26 13:51:10',
            ),
            8 =>
            array (
                'id' => 9,
                'name' => 'Richard K. Ellison',
                'email' => 'RichardKEllison@teleworm.us',
                'primary_number' => '703-462-8233',
                'secondary_number' => '',
                'address' => '376 Melody Lane',
                'zipcode' => '22102',
                'city' => 'McLean',
                'state' => 'VA',
                'company_name' => 'Merrill Lynch',
                'status' => 1,
                'group_id' => 1,
                'user_id' => 1,
                'industry_id' => 1,
                'created_at' => '2017-11-26 13:51:10',
                'updated_at' => '2017-11-26 13:51:10',
            ),
            9 =>
            array (
                'id' => 10,
                'name' => 'Nancy W. Kinnard',
                'email' => 'NancyWKinnard@jourrapide.com',
                'primary_number' => '703-249-6770',
                'secondary_number' => '',
                'address' => '547 Elk Rd Little',
                'zipcode' => '20148',
                'city' => 'Ashburn',
                'state' => 'VA',
                'company_name' => 'Purity Supreme',
                'status' => 1,
                'group_id' => 1,
                'user_id' => 1,
                'industry_id' => 1,
                'created_at' => '2017-11-26 13:51:10',
                'updated_at' => '2017-11-26 13:51:10',
            ),
            10 =>
            array (
                'id' => 11,
                'name' => 'Nicole C. Manners',
                'email' => 'NicoleCManners@teleworm.us',
                'primary_number' => '240-678-4838',
                'secondary_number' => '',
                'address' => '3205 West Street',
                'zipcode' => '22152',
                'city' => 'Springfield',
                'state' => 'VA',
                'company_name' => 'DGS HomeSource',
                'status' => 1,
                'group_id' => 1,
                'user_id' => 1,
                'industry_id' => 1,
                'created_at' => '2017-11-26 13:51:10',
                'updated_at' => '2017-11-26 13:51:10',
            ),
            11 =>
            array (
                'id' => 12,
                'name' => 'Erin S. Wright',
                'email' => 'ErinSWright@teleworm.us',
                'primary_number' => '240-264-1726',
                'secondary_number' => '',
                'address' => '4343 Oakridge Lane',
                'zipcode' => '22152',
                'city' => 'Springfield',
                'state' => 'VA',
                'company_name' => 'Grodins',
                'status' => 1,
                'group_id' => 1,
                'user_id' => 1,
                'industry_id' => 1,
                'created_at' => '2017-11-26 13:51:10',
                'updated_at' => '2017-11-26 13:51:10',
            ),
            12 =>
            array (
                'id' => 13,
                'name' => 'Donald L. Moore',
                'email' => 'DonaldLMoore@jourrapide.com',
                'primary_number' => '703-864-4096',
                'secondary_number' => '',
                'address' => '1588 Poe Road',
                'zipcode' => '22102',
                'city' => 'McLean',
                'state' => 'VA',
                'company_name' => 'Action Auto',
                'status' => 1,
                'group_id' => 1,
                'user_id' => 1,
                'industry_id' => 1,
                'created_at' => '2017-11-26 13:51:10',
                'updated_at' => '2017-11-26 13:51:10',
            ),
            13 =>
            array (
                'id' => 14,
                'name' => 'Dann S. King',
                'email' => 'DannSKing@armyspy.com',
                'primary_number' => '703-755-1488',
                'secondary_number' => '',
                'address' => '333 Perine Street',
                'zipcode' => '20148',
                'city' => 'Ashburn',
                'state' => 'VA',
                'company_name' => 'Miller & Rhoads',
                'status' => 1,
                'group_id' => 1,
                'user_id' => 1,
                'industry_id' => 1,
                'created_at' => '2017-11-26 13:51:10',
                'updated_at' => '2017-11-26 13:51:10',
            ),
            14 =>
            array (
                'id' => 15,
                'name' => 'Debby R. Baldwin',
                'email' => 'DebbyRBaldwin@rhyta.com',
                'primary_number' => '240-665-9433',
                'secondary_number' => '',
                'address' => '4175 Drainer Avenue',
                'zipcode' => '22152',
                'city' => 'Springfield',
                'state' => 'VA',
                'company_name' => 'Playworld',
                'status' => 1,
                'group_id' => 1,
                'user_id' => 1,
                'industry_id' => 1,
                'created_at' => '2017-11-26 13:51:10',
                'updated_at' => '2017-11-26 13:51:10',
            ),
            15 =>
            array (
                'id' => 16,
                'name' => 'Charles S. Muir',
                'email' => 'CharlesSMuir@jourrapide.com',
                'primary_number' => '240-471-8384',
                'secondary_number' => '',
                'address' => '72 Benson Park Drive',
                'zipcode' => '22152',
                'city' => 'Springfield',
                'state' => 'VA',
                'company_name' => 'Team Uno',
                'status' => 1,
                'group_id' => 1,
                'user_id' => 1,
                'industry_id' => 1,
                'created_at' => '2017-11-26 13:51:10',
                'updated_at' => '2017-11-26 13:51:10',
            ),
            16 =>
            array (
                'id' => 17,
                'name' => 'Jeffrey K. Depriest',
                'email' => 'JeffreyKDepriest@dayrep.com',
                'primary_number' => '703-989-0383',
                'secondary_number' => '',
                'address' => '3788 Hummingbird Way',
                'zipcode' => '22102',
                'city' => 'McLean',
                'state' => 'VA',
                'company_name' => 'Planetbiz',
                'status' => 1,
                'group_id' => 1,
                'user_id' => 1,
                'industry_id' => 1,
                'created_at' => '2017-11-26 13:51:10',
                'updated_at' => '2017-11-26 13:51:10',
            ),
            17 =>
            array (
                'id' => 18,
                'name' => 'Peter S. Whitmore',
                'email' => 'PeterSWhitmore@dayrep.com',
                'primary_number' => '703-315-0238',
                'secondary_number' => '',
                'address' => '3824 Ashmor Drive',
                'zipcode' => '20148',
                'city' => 'Ashburn',
                'state' => 'VA',
                'company_name' => 'Jacob Reed and Sons',
                'status' => 1,
                'group_id' => 1,
                'user_id' => 1,
                'industry_id' => 1,
                'created_at' => '2017-11-26 13:51:10',
                'updated_at' => '2017-11-26 13:51:10',
            ),
            18 =>
            array (
                'id' => 19,
                'name' => 'Krystal G. Ugarte',
                'email' => 'KrystalGUgarte@armyspy.com',
                'primary_number' => '240-255-7228',
                'secondary_number' => '',
                'address' => '4273 Catherine Drive',
                'zipcode' => '22152',
                'city' => 'Springfield',
                'state' => 'VA',
                'company_name' => 'Payless Cashways',
                'status' => 1,
                'group_id' => 1,
                'user_id' => 1,
                'industry_id' => 1,
                'created_at' => '2017-11-26 13:51:10',
                'updated_at' => '2017-11-26 13:51:10',
            ),
            19 =>
            array (
                'id' => 20,
                'name' => 'Daniel D. Phillips',
                'email' => 'DanielDPhillips@dayrep.com',
                'primary_number' => '240-925-8985',
                'secondary_number' => '',
                'address' => '1446 Hope Street',
                'zipcode' => '22152',
                'city' => 'Springfield',
                'state' => 'VA',
                'company_name' => 'A Plus Lawn Care',
                'status' => 1,
                'group_id' => 1,
                'user_id' => 1,
                'industry_id' => 1,
                'created_at' => '2017-11-26 13:51:10',
                'updated_at' => '2017-11-26 13:51:10',
            ),
            20 =>
            array (
                'id' => 21,
                'name' => 'Michael Reyes',
                'email' => 'michael.p.reyes@ml.com ',
                'primary_number' => '703-663-2909',
                'secondary_number' => '',
                'address' => '8300 Greensboro Drive, 1st Floor',
                'zipcode' => '22102',
                'city' => 'McLean',
                'state' => 'VA',
                'company_name' => 'Merrill Lynch',
                'status' => 1,
                'group_id' => 4,
                'user_id' => 1,
                'industry_id' => 1,
                'created_at' => '2017-11-26 13:51:10',
                'updated_at' => '2017-11-26 13:51:10',
            ),
            21 =>
            array (
                'id' => 22,
                'name' => 'Seong Bae',
                'email' => 'seong@lnidigital.com',
                'primary_number' => '703-955-6819',
                'secondary_number' => '',
                'address' => '42466 Legacy Park Drive',
                'zipcode' => '20148',
                'city' => 'Ashburn',
                'state' => 'VA',
                'company_name' => 'LNI Digital Marketing',
                'status' => 1,
                'group_id' => 4,
                'user_id' => 1,
                'industry_id' => 1,
                'created_at' => '2017-11-26 13:51:10',
                'updated_at' => '2017-11-26 13:51:10',
            ),
            22 =>
            array (
                'id' => 23,
                'name' => 'Sunny Luk',
                'email' => 'Lukfinancialgroup@gmail.com',
                'primary_number' => '240-386-9508',
                'secondary_number' => '',
                'address' => '6608 Green Ash ct',
                'zipcode' => '22152',
                'city' => 'Springfield',
                'state' => 'VA',
                'company_name' => 'Luk Financial Group',
                'status' => 1,
                'group_id' => 4,
                'user_id' => 1,
                'industry_id' => 1,
                'created_at' => '2017-11-26 13:51:10',
                'updated_at' => '2017-11-26 13:51:10',
            ),
            23 =>
            array (
                'id' => 24,
                'name' => 'Dave Estep',
                'email' => 'destep@olmstedfoundation.org',
                'primary_number' => '240-386-9508',
                'secondary_number' => '',
                'address' => '6608 Green Ash ct',
                'zipcode' => '22152',
                'city' => 'Springfield',
                'state' => 'VA',
                'company_name' => 'The Olmsted Foundation',
                'status' => 2,
                'group_id' => 4,
                'user_id' => 1,
                'industry_id' => 1,
                'created_at' => '2017-11-26 13:51:10',
                'updated_at' => '2017-11-26 13:51:10',
            ),
            24 =>
            array (
                'id' => 25,
                'name' => 'Robert McCroy',
                'email' => 'robertsmccroy@dayrep.com ',
                'primary_number' => '703-517-9656',
                'secondary_number' => '',
                'address' => '4244 Gregory Lane',
                'zipcode' => '22102',
                'city' => 'McLean',
                'state' => 'VA',
                'company_name' => 'Merrill Lynch',
                'status' => 1,
                'group_id' => 6,
                'user_id' => 1,
                'industry_id' => 1,
                'created_at' => '2017-11-26 13:51:10',
                'updated_at' => '2017-11-26 13:51:10',
            ),
            25 =>
            array (
                'id' => 26,
                'name' => 'Charles Marquart',
                'email' => 'CharlesJMarquart@dayrep.com',
                'primary_number' => '703-767-8007',
                'secondary_number' => '',
                'address' => '3753 Tea Berry Lane',
                'zipcode' => '20148',
                'city' => 'Ashburn',
                'state' => 'VA',
                'company_name' => 'Rogersound Labs',
                'status' => 1,
                'group_id' => 6,
                'user_id' => 1,
                'industry_id' => 2,
                'created_at' => '2017-11-26 13:51:10',
                'updated_at' => '2017-11-26 13:51:10',
            ),
            26 =>
            array (
                'id' => 27,
                'name' => 'Angela Smith',
                'email' => 'AngelaDSmith@dayrep.com',
                'primary_number' => '240-386-9508',
                'secondary_number' => '',
                'address' => '6608 Green Ash ct',
                'zipcode' => '22152',
                'city' => 'Falls Church',
                'state' => 'VA',
                'company_name' => 'Pomeroy\'s',
                'status' => 1,
                'group_id' => 6,
                'user_id' => 1,
                'industry_id' => 3,
                'created_at' => '2017-11-26 13:51:10',
                'updated_at' => '2017-11-26 13:51:10',
            ),
            27 =>
            array (
                'id' => 28,
                'name' => 'Brandon Fox',
                'email' => 'BrandonFox@teleworm.us',
                'primary_number' => '240-224-5125',
                'secondary_number' => '',
                'address' => '1521 Freshour Circle',
                'zipcode' => '22152',
                'city' => 'Centreville',
                'state' => 'VA',
                'company_name' => 'White Coffee Pot',
                'status' => 1,
                'group_id' => 6,
                'user_id' => 1,
                'industry_id' => 4,
                'created_at' => '2017-11-26 13:51:10',
                'updated_at' => '2017-11-26 13:51:10',
            ),
            28 =>
            array (
                'id' => 29,
                'name' => 'Timmy Owenby',
                'email' => 'TimmyDOwenby@jourrapide.com',
                'primary_number' => '703-616-3241',
                'secondary_number' => '',
                'address' => '3508 Parrill Court',
                'zipcode' => '22102',
                'city' => 'McLean',
                'state' => 'VA',
                'company_name' => 'Brendle\'s',
                'status' => 1,
                'group_id' => 6,
                'user_id' => 1,
                'industry_id' => 5,
                'created_at' => '2017-11-26 13:51:10',
                'updated_at' => '2017-11-26 13:51:10',
            ),
            29 =>
            array (
                'id' => 30,
                'name' => 'Chelsie Barker',
                'email' => 'ChelsieGBarker@dayrep.com',
                'primary_number' => '703-955-6819',
                'secondary_number' => '',
                'address' => '3368 Quilly Lane',
                'zipcode' => '20148',
                'city' => 'Ashburn',
                'state' => 'VA',
                'company_name' => 'Action Auto',
                'status' => 1,
                'group_id' => 6,
                'user_id' => 1,
                'industry_id' => 1,
                'created_at' => '2017-11-26 13:51:10',
                'updated_at' => '2017-11-26 13:51:10',
            ),
            30 =>
            array (
                'id' => 31,
                'name' => 'Martha J. Isaac',
                'email' => 'MarthaJIsaac@armyspy.com',
                'primary_number' => '240-294-1599',
                'secondary_number' => '',
                'address' => '2632 Red Dog Road',
                'zipcode' => '22152',
                'city' => 'Springfield',
                'state' => 'VA',
                'company_name' => 'L.L. Berger',
                'status' => 1,
                'group_id' => 6,
                'user_id' => 1,
                'industry_id' => 1,
                'created_at' => '2017-11-26 13:51:10',
                'updated_at' => '2017-11-26 13:51:10',
            ),
            31 =>
            array (
                'id' => 32,
                'name' => 'Clinton Turner',
                'email' => 'ClintonBTurner@dayrep.com',
                'primary_number' => '240-258-2963',
                'secondary_number' => '',
                'address' => '1030 Cecil Street',
                'zipcode' => '22152',
                'city' => 'Springfield',
                'state' => 'VA',
                'company_name' => 'J. Riggings',
                'status' => 1,
                'group_id' => 6,
                'user_id' => 1,
                'industry_id' => 1,
                'created_at' => '2017-11-26 13:51:10',
                'updated_at' => '2017-11-26 13:51:10',
            ),
            32 =>
            array (
                'id' => 33,
                'name' => 'Richard Ellison',
                'email' => 'RichardKEllison@teleworm.us',
                'primary_number' => '703-462-8233',
                'secondary_number' => '',
                'address' => '376 Melody Lane',
                'zipcode' => '22102',
                'city' => 'McLean',
                'state' => 'VA',
                'company_name' => 'Merrill Lynch',
                'status' => 1,
                'group_id' => 6,
                'user_id' => 1,
                'industry_id' => 1,
                'created_at' => '2017-11-26 13:51:10',
                'updated_at' => '2017-11-26 13:51:10',
            ),
            33 =>
            array (
                'id' => 34,
                'name' => 'Nancy Kinnard',
                'email' => 'NancyWKinnard@jourrapide.com',
                'primary_number' => '703-249-6770',
                'secondary_number' => '',
                'address' => '547 Elk Rd Little',
                'zipcode' => '20148',
                'city' => 'Ashburn',
                'state' => 'VA',
                'company_name' => 'Purity Supreme',
                'status' => 1,
                'group_id' => 6,
                'user_id' => 1,
                'industry_id' => 1,
                'created_at' => '2017-11-26 13:51:10',
                'updated_at' => '2017-11-26 13:51:10',
            ),
            34 =>
            array (
                'id' => 35,
                'name' => 'Nicole Manners',
                'email' => 'NicoleCManners@teleworm.us',
                'primary_number' => '240-678-4838',
                'secondary_number' => '',
                'address' => '3205 West Street',
                'zipcode' => '22152',
                'city' => 'Springfield',
                'state' => 'VA',
                'company_name' => 'DGS HomeSource',
                'status' => 1,
                'group_id' => 6,
                'user_id' => 1,
                'industry_id' => 1,
                'created_at' => '2017-11-26 13:51:10',
                'updated_at' => '2017-11-26 13:51:10',
            ),
            35 =>
            array (
                'id' => 36,
                'name' => 'Erin Wright',
                'email' => 'ErinSWright@teleworm.us',
                'primary_number' => '240-264-1726',
                'secondary_number' => '',
                'address' => '4343 Oakridge Lane',
                'zipcode' => '22152',
                'city' => 'Springfield',
                'state' => 'VA',
                'company_name' => 'Grodins',
                'status' => 1,
                'group_id' => 6,
                'user_id' => 1,
                'industry_id' => 1,
                'created_at' => '2017-11-26 13:51:10',
                'updated_at' => '2017-11-26 13:51:10',
            ),
            36 =>
            array (
                'id' => 37,
                'name' => 'Donald Moore',
                'email' => 'DonaldLMoore@jourrapide.com',
                'primary_number' => '703-864-4096',
                'secondary_number' => '',
                'address' => '1588 Poe Road',
                'zipcode' => '22102',
                'city' => 'McLean',
                'state' => 'VA',
                'company_name' => 'Action Auto',
                'status' => 1,
                'group_id' => 6,
                'user_id' => 1,
                'industry_id' => 1,
                'created_at' => '2017-11-26 13:51:10',
                'updated_at' => '2017-11-26 13:51:10',
            ),
            37 =>
            array (
                'id' => 38,
                'name' => 'Dann King',
                'email' => 'DannSKing@armyspy.com',
                'primary_number' => '703-755-1488',
                'secondary_number' => '',
                'address' => '333 Perine Street',
                'zipcode' => '20148',
                'city' => 'Ashburn',
                'state' => 'VA',
                'company_name' => 'Miller & Rhoads',
                'status' => 1,
                'group_id' => 6,
                'user_id' => 1,
                'industry_id' => 1,
                'created_at' => '2017-11-26 13:51:10',
                'updated_at' => '2017-11-26 13:51:10',
            ),
            38 =>
            array (
                'id' => 39,
                'name' => 'Debby Baldwin',
                'email' => 'DebbyRBaldwin@rhyta.com',
                'primary_number' => '240-665-9433',
                'secondary_number' => '',
                'address' => '4175 Drainer Avenue',
                'zipcode' => '22152',
                'city' => 'Springfield',
                'state' => 'VA',
                'company_name' => 'Playworld',
                'status' => 1,
                'group_id' => 6,
                'user_id' => 1,
                'industry_id' => 1,
                'created_at' => '2017-11-26 13:51:10',
                'updated_at' => '2017-11-26 13:51:10',
            ),
            39 =>
            array (
                'id' => 40,
                'name' => 'Charles S. Muir',
                'email' => 'CharlesSMuir@jourrapide.com',
                'primary_number' => '240-471-8384',
                'secondary_number' => '',
                'address' => '72 Benson Park Drive',
                'zipcode' => '22152',
                'city' => 'Springfield',
                'state' => 'VA',
                'company_name' => 'Team Uno',
                'status' => 1,
                'group_id' => 6,
                'user_id' => 1,
                'industry_id' => 1,
                'created_at' => '2017-11-26 13:51:10',
                'updated_at' => '2017-11-26 13:51:10',
            ),
            40 =>
            array (
                'id' => 41,
                'name' => 'Jeffrey Depriest',
                'email' => 'JeffreyKDepriest@dayrep.com',
                'primary_number' => '703-989-0383',
                'secondary_number' => '',
                'address' => '3788 Hummingbird Way',
                'zipcode' => '22102',
                'city' => 'McLean',
                'state' => 'VA',
                'company_name' => 'Planetbiz',
                'status' => 1,
                'group_id' => 6,
                'user_id' => 1,
                'industry_id' => 1,
                'created_at' => '2017-11-26 13:51:10',
                'updated_at' => '2017-11-26 13:51:10',
            ),
            41 =>
            array (
                'id' => 42,
                'name' => 'Peter Whitmore',
                'email' => 'PeterSWhitmore@dayrep.com',
                'primary_number' => '703-315-0238',
                'secondary_number' => '',
                'address' => '3824 Ashmor Drive',
                'zipcode' => '20148',
                'city' => 'Ashburn',
                'state' => 'VA',
                'company_name' => 'Jacob Reed and Sons',
                'status' => 1,
                'group_id' => 6,
                'user_id' => 1,
                'industry_id' => 1,
                'created_at' => '2017-11-26 13:51:10',
                'updated_at' => '2017-11-26 13:51:10',
            ),
            42 =>
            array (
                'id' => 43,
                'name' => 'Krystal Ugarte',
                'email' => 'KrystalGUgarte@armyspy.com',
                'primary_number' => '240-255-7228',
                'secondary_number' => '',
                'address' => '4273 Catherine Drive',
                'zipcode' => '22152',
                'city' => 'Springfield',
                'state' => 'VA',
                'company_name' => 'Payless Cashways',
                'status' => 1,
                'group_id' => 6,
                'user_id' => 1,
                'industry_id' => 1,
                'created_at' => '2017-11-26 13:51:10',
                'updated_at' => '2017-11-26 13:51:10',
            ),
            43 =>
            array (
                'id' => 44,
                'name' => 'Daniel Phillips',
                'email' => 'DanielDPhillips@dayrep.com',
                'primary_number' => '240-925-8985',
                'secondary_number' => '',
                'address' => '1446 Hope Street',
                'zipcode' => '22152',
                'city' => 'Springfield',
                'state' => 'VA',
                'company_name' => 'A Plus Lawn Care',
                'status' => 1,
                'group_id' => 6,
                'user_id' => 1,
                'industry_id' => 1,
                'created_at' => '2017-11-26 13:51:10',
                'updated_at' => '2017-11-26 13:51:10',
            ),
            44 =>
            array (
                'id' => 45,
                'name' => 'Mindy Jennings',
                'email' => 'MindyJennings@dayrep.com ',
                'primary_number' => '703-517-9656',
                'secondary_number' => '',
                'address' => '4244 Gregory Lane',
                'zipcode' => '22102',
                'city' => 'McLean',
                'state' => 'VA',
                'company_name' => 'Merrill Lynch',
                'status' => 2,
                'group_id' => 6,
                'user_id' => 1,
                'industry_id' => 1,
                'created_at' => '2017-11-26 13:51:10',
                'updated_at' => '2017-11-26 13:51:10',
            ),
            45 =>
            array (
                'id' => 46,
                'name' => 'Byron Walsh',
                'email' => 'ByronWalsh@dayrep.com',
                'primary_number' => '703-767-8007',
                'secondary_number' => '',
                'address' => '3753 Tea Berry Lane',
                'zipcode' => '20148',
                'city' => 'Ashburn',
                'state' => 'VA',
                'company_name' => 'Rogersound Labs',
                'status' => 2,
                'group_id' => 6,
                'user_id' => 1,
                'industry_id' => 2,
                'created_at' => '2017-11-26 13:51:10',
                'updated_at' => '2017-11-26 13:51:10',
            ),
            46 =>
            array (
                'id' => 47,
                'name' => 'Marilyn Mack',
                'email' => 'MarilynMack@dayrep.com',
                'primary_number' => '240-386-9508',
                'secondary_number' => '',
                'address' => '6608 Green Ash ct',
                'zipcode' => '22152',
                'city' => 'Falls Church',
                'state' => 'VA',
                'company_name' => 'Pomeroy\'s',
                'status' => 2,
                'group_id' => 6,
                'user_id' => 1,
                'industry_id' => 3,
                'created_at' => '2017-11-26 13:51:10',
                'updated_at' => '2017-11-26 13:51:10',
            ),
            47 =>
            array (
                'id' => 48,
                'name' => 'Brandon B. Fox',
                'email' => 'BrandonBFox@teleworm.us',
                'primary_number' => '240-224-5125',
                'secondary_number' => '',
                'address' => '1521 Freshour Circle',
                'zipcode' => '22152',
                'city' => 'Centreville',
                'state' => 'VA',
                'company_name' => 'White Coffee Pot',
                'status' => 2,
                'group_id' => 6,
                'user_id' => 1,
                'industry_id' => 4,
                'created_at' => '2017-11-26 13:51:10',
                'updated_at' => '2017-11-26 13:51:10',
            ),
            48 =>
            array (
                'id' => 49,
                'name' => 'Salvatore Robertson',
                'email' => 'SalvatoreRobertson@jourrapide.com',
                'primary_number' => '703-616-3241',
                'secondary_number' => '',
                'address' => '3508 Parrill Court',
                'zipcode' => '22102',
                'city' => 'McLean',
                'state' => 'VA',
                'company_name' => 'Brendle\'s',
                'status' => 2,
                'group_id' => 6,
                'user_id' => 1,
                'industry_id' => 5,
                'created_at' => '2017-11-26 13:51:10',
                'updated_at' => '2017-11-26 13:51:10',
            ),
            49 =>
            array (
                'id' => 50,
                'name' => 'Billie Mcdaniel',
                'email' => 'BillieMcdaniel@dayrep.com',
                'primary_number' => '703-955-6819',
                'secondary_number' => '',
                'address' => '3368 Quilly Lane',
                'zipcode' => '20148',
                'city' => 'Ashburn',
                'state' => 'VA',
                'company_name' => 'Action Auto',
                'status' => 2,
                'group_id' => 6,
                'user_id' => 1,
                'industry_id' => 1,
                'created_at' => '2017-11-26 13:51:10',
                'updated_at' => '2017-11-26 13:51:10',
            ),
            50 =>
            array (
                'id' => 51,
                'name' => 'Terry Aguilar',
                'email' => 'TerryAguilar@armyspy.com',
                'primary_number' => '240-294-1599',
                'secondary_number' => '',
                'address' => '2632 Red Dog Road',
                'zipcode' => '22152',
                'city' => 'Springfield',
                'state' => 'VA',
                'company_name' => 'L.L. Berger',
                'status' => 2,
                'group_id' => 6,
                'user_id' => 1,
                'industry_id' => 1,
                'created_at' => '2017-11-26 13:51:10',
                'updated_at' => '2017-11-26 13:51:10',
            ),
            51 =>
            array (
                'id' => 52,
                'name' => 'Estelle Ortega',
                'email' => 'EstelleOrtega@dayrep.com',
                'primary_number' => '240-258-2963',
                'secondary_number' => '',
                'address' => '1030 Cecil Street',
                'zipcode' => '22152',
                'city' => 'Springfield',
                'state' => 'VA',
                'company_name' => 'J. Riggings',
                'status' => 2,
                'group_id' => 6,
                'user_id' => 1,
                'industry_id' => 1,
                'created_at' => '2017-11-26 13:51:10',
                'updated_at' => '2017-11-26 13:51:10',
            ),
            52 =>
            array (
                'id' => 53,
                'name' => 'Raquel Jacobs',
                'email' => 'RaquelJacobs@teleworm.us',
                'primary_number' => '703-462-8233',
                'secondary_number' => '',
                'address' => '376 Melody Lane',
                'zipcode' => '22102',
                'city' => 'McLean',
                'state' => 'VA',
                'company_name' => 'Merrill Lynch',
                'status' => 2,
                'group_id' => 6,
                'user_id' => 1,
                'industry_id' => 1,
                'created_at' => '2017-11-26 13:51:10',
                'updated_at' => '2017-11-26 13:51:10',
            ),
            53 =>
            array (
                'id' => 54,
                'name' => 'Jared Harmon',
                'email' => 'JaredHarmon@jourrapide.com',
                'primary_number' => '703-249-6770',
                'secondary_number' => '',
                'address' => '547 Elk Rd Little',
                'zipcode' => '20148',
                'city' => 'Ashburn',
                'state' => 'VA',
                'company_name' => 'Purity Supreme',
                'status' => 2,
                'group_id' => 6,
                'user_id' => 1,
                'industry_id' => 1,
                'created_at' => '2017-11-26 13:51:10',
                'updated_at' => '2017-11-26 13:51:10',
            ),
            54 =>
            array (
                'id' => 55,
                'name' => 'Lowell Kelly',
                'email' => 'LowellKelly@teleworm.us',
                'primary_number' => '240-678-4838',
                'secondary_number' => '',
                'address' => '3205 West Street',
                'zipcode' => '22152',
                'city' => 'Springfield',
                'state' => 'VA',
                'company_name' => 'DGS HomeSource',
                'status' => 2,
                'group_id' => 6,
                'user_id' => 1,
                'industry_id' => 1,
                'created_at' => '2017-11-26 13:51:10',
                'updated_at' => '2017-11-26 13:51:10',
            ),
            55 =>
            array (
                'id' => 56,
                'name' => 'StaceyRamos',
                'email' => 'StaceyRamos@teleworm.us',
                'primary_number' => '240-264-1726',
                'secondary_number' => '',
                'address' => '4343 Oakridge Lane',
                'zipcode' => '22152',
                'city' => 'Springfield',
                'state' => 'VA',
                'company_name' => 'Grodins',
                'status' => 2,
                'group_id' => 6,
                'user_id' => 1,
                'industry_id' => 1,
                'created_at' => '2017-11-26 13:51:10',
                'updated_at' => '2017-11-26 13:51:10',
            ),
            56 =>
            array (
                'id' => 57,
                'name' => 'Bernadette Maxwell',
                'email' => 'BernadetteMaxwell@jourrapide.com',
                'primary_number' => '703-864-4096',
                'secondary_number' => '',
                'address' => '1588 Poe Road',
                'zipcode' => '22102',
                'city' => 'McLean',
                'state' => 'VA',
                'company_name' => 'Action Auto',
                'status' => 2,
                'group_id' => 6,
                'user_id' => 1,
                'industry_id' => 1,
                'created_at' => '2017-11-26 13:51:10',
                'updated_at' => '2017-11-26 13:51:10',
            ),
            57 =>
            array (
                'id' => 58,
                'name' => 'Lydia Reed',
                'email' => 'LydiaReed@armyspy.com',
                'primary_number' => '703-755-1488',
                'secondary_number' => '',
                'address' => '333 Perine Street',
                'zipcode' => '20148',
                'city' => 'Ashburn',
                'state' => 'VA',
                'company_name' => 'Miller & Rhoads',
                'status' => 2,
                'group_id' => 6,
                'user_id' => 1,
                'industry_id' => 1,
                'created_at' => '2017-11-26 13:51:10',
                'updated_at' => '2017-11-26 13:51:10',
            ),
            58 =>
            array (
                'id' => 59,
                'name' => 'SpencerGreer',
                'email' => 'SpencerGreer@rhyta.com',
                'primary_number' => '240-665-9433',
                'secondary_number' => '',
                'address' => '4175 Drainer Avenue',
                'zipcode' => '22152',
                'city' => 'Springfield',
                'state' => 'VA',
                'company_name' => 'Playworld',
                'status' => 2,
                'group_id' => 6,
                'user_id' => 1,
                'industry_id' => 1,
                'created_at' => '2017-11-26 13:51:10',
                'updated_at' => '2017-11-26 13:51:10',
            ),
            59 =>
            array (
                'id' => 60,
                'name' => 'Pam Ford',
                'email' => 'PamFord@jourrapide.com',
                'primary_number' => '240-471-8384',
                'secondary_number' => '',
                'address' => '72 Benson Park Drive',
                'zipcode' => '22152',
                'city' => 'Springfield',
                'state' => 'VA',
                'company_name' => 'Team Uno',
                'status' => 2,
                'group_id' => 6,
                'user_id' => 1,
                'industry_id' => 1,
                'created_at' => '2017-11-26 13:51:10',
                'updated_at' => '2017-11-26 13:51:10',
            ),
            60 =>
            array (
                'id' => 61,
                'name' => 'Nancy Singleton',
                'email' => 'NancySingleton@dayrep.com',
                'primary_number' => '703-989-0383',
                'secondary_number' => '',
                'address' => '3788 Hummingbird Way',
                'zipcode' => '22102',
                'city' => 'McLean',
                'state' => 'VA',
                'company_name' => 'Planetbiz',
                'status' => 2,
                'group_id' => 6,
                'user_id' => 1,
                'industry_id' => 1,
                'created_at' => '2017-11-26 13:51:10',
                'updated_at' => '2017-11-26 13:51:10',
            ),
            61 =>
            array (
                'id' => 62,
                'name' => 'Guy Cohen',
                'email' => 'GuyCohen@dayrep.com',
                'primary_number' => '703-315-0238',
                'secondary_number' => '',
                'address' => '3824 Ashmor Drive',
                'zipcode' => '20148',
                'city' => 'Ashburn',
                'state' => 'VA',
                'company_name' => 'Jacob Reed and Sons',
                'status' => 2,
                'group_id' => 6,
                'user_id' => 1,
                'industry_id' => 1,
                'created_at' => '2017-11-26 13:51:10',
                'updated_at' => '2017-11-26 13:51:10',
            ),
            62 =>
            array (
                'id' => 63,
                'name' => 'Robin Dean',
                'email' => 'RobinDean@armyspy.com',
                'primary_number' => '240-255-7228',
                'secondary_number' => '',
                'address' => '4273 Catherine Drive',
                'zipcode' => '22152',
                'city' => 'Springfield',
                'state' => 'VA',
                'company_name' => 'Payless Cashways',
                'status' => 2,
                'group_id' => 6,
                'user_id' => 1,
                'industry_id' => 1,
                'created_at' => '2017-11-26 13:51:10',
                'updated_at' => '2017-11-26 13:51:10',
            ),
            63 =>
            array (
                'id' => 64,
                'name' => 'Mack Shaw',
                'email' => 'MackShaw@dayrep.com',
                'primary_number' => '240-925-8985',
                'secondary_number' => '',
                'address' => '1446 Hope Street',
                'zipcode' => '22152',
                'city' => 'Springfield',
                'state' => 'VA',
                'company_name' => 'A Plus Lawn Care',
                'status' => 2,
                'group_id' => 6,
                'user_id' => 1,
                'industry_id' => 1,
                'created_at' => '2017-11-26 13:51:10',
                'updated_at' => '2017-11-26 13:51:10',
            ),
            64 =>
            array (
                'id' => 65,
                'name' => 'Joey Perkins',
                'email' => 'JoeyPerkins@ml.com ',
                'primary_number' => '703-663-2909',
                'secondary_number' => '',
                'address' => '8300 Greensboro Drive, 1st Floor',
                'zipcode' => '22102',
                'city' => 'McLean',
                'state' => 'VA',
                'company_name' => 'Merrill Lynch',
                'status' => 2,
                'group_id' => 4,
                'user_id' => 1,
                'industry_id' => 1,
                'created_at' => '2017-11-26 13:51:10',
                'updated_at' => '2017-11-26 13:51:10',
            ),
        ));
    }
}
